/*
  build.js — Netlify Build Script
  ────────────────────────────────
  Netlify runs this BEFORE deploying (see netlify.toml).

  It reads your Spotify Client ID from the SPOTIFY_CLIENT_ID
  environment variable (set in Netlify's dashboard under
  Site Settings → Environment Variables) and writes config.js
  to disk so the browser can use it at runtime.

  If the env var is missing, the build FAILS on purpose —
  deploying without a client ID would result in a broken app.

  No npm packages are needed. This uses only Node.js built-ins.
*/

const fs = require('fs');

// ── 1. Read the environment variable ────────────────
const clientId = process.env.SPOTIFY_CLIENT_ID || '';

if (!clientId) {
  console.error('');
  console.error('╔══════════════════════════════════════════════════╗');
  console.error('║  BUILD ERROR: SPOTIFY_CLIENT_ID is not set!     ║');
  console.error('║                                                  ║');
  console.error('║  Go to Netlify → Site Settings → Environment    ║');
  console.error('║  Variables and add SPOTIFY_CLIENT_ID.            ║');
  console.error('╚══════════════════════════════════════════════════╝');
  console.error('');
  process.exit(1);
}

// ── 2. Build the config.js file contents ────────────
//    This must produce the EXACT same shape as config.example.js
//    so that spotify.js and all other scripts work identically.

const configContent = `/*
  config.js — Auto-generated by build.js on ${new Date().toISOString()}
  DO NOT EDIT — this file is overwritten on every Netlify deploy.
*/

const APP_CONFIG = {
  spotifyClientId: '${clientId}',
};

const SPOTIFY_CONFIG = {
  clientId: APP_CONFIG.spotifyClientId,
  redirectUri: window.location.origin,
  scopes: [
    'streaming',
    'user-read-email',
    'user-read-private',
    'playlist-read-private',
    'playlist-read-collaborative',
    'user-modify-playback-state',
    'user-read-playback-state',
  ].join(' '),
};

const AUTH_CONFIG = {
  storageKeys: {
    token:        'spotify_token',
    refreshToken: 'spotify_refresh_token',
    tokenExpiry:  'spotify_token_expiry',
    verifier:     'spotify_verifier',
    deviceId:     'spotify_device_id',
  },
  expiryBufferMs: 60000,
  tokenEndpoint: 'https://accounts.spotify.com/api/token',
  authorizeEndpoint: 'https://accounts.spotify.com/authorize',
  apiBase: 'https://api.spotify.com',
};

const SECURITY_CONFIG = {
  pkceMethod: 'S256',
  verifierLength: 64,
  allowedOrigins: [
    'https://accounts.spotify.com',
    'https://api.spotify.com',
    'https://sdk.scdn.co',
    'https://fonts.googleapis.com',
    'https://fonts.gstatic.com',
    'https://cdn.jsdelivr.net',
    'https://i.scdn.co',
  ],
  maxTokenRetries: 1,
  clearOnLogout: true,
};

const PLAYBACK_CONFIG = {
  defaultVolume: 0.8,
  progressPollInterval: 1000,
  sdkReadyTimeout: 5000,
};
`;

// ── 3. Write the file ───────────────────────────────
fs.writeFileSync('config.js', configContent, 'utf-8');

console.log('[BUILD] ✓ config.js written successfully.');
console.log('[BUILD]   Client ID: ' + clientId.slice(0, 6) + '...' + clientId.slice(-4));
